arch:
  - amd64
  - arm64
os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
# command to install dependencies
install:
  - pip install .
# command to run tests
before_script:
  - pip install -U pytest yagot gevent
  - pip install git+https://github.com/congma/trackrefcount.git#egg=trackrefcount
script:
  - pytest
