name: GitHub CI


on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

  workflow_dispatch:


jobs:
  build-and-test-with-pythons-on-focal:
    name: Build and Test on Ubuntu 20
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python repository (excl. 3.8, 3.10)
      if: matrix.python-version != 3.8 && matrix.python-version != 3.10
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update

    - name: Set up Python repository (3.8)
      if: matrix.python-version == 3.8
      run: sudo apt-get update

    - name: Set up Python repository (3.10)
      if: matrix.python-version == 3.10
      run: |
        sudo add-apt-repository ppa:deadsnakes/nightly
        sudo apt-get update

    - name: Install dependencies (excl. 3.10)
      if: matrix.python-version != 3.10
      run: |
        sudo apt-get install -y --no-install-recommends python${{ matrix.python-version }}-dev
        python${{ matrix.python-version }} -m pip install --upgrade pip setuptools pytest

    - name: Install dependencies (3.10)
      if: matrix.python-version == 3.10
      run: |
        sudo apt-get install -y --no-install-recommends python${{ matrix.python-version }}-dev python${{ matrix.python-version }}-distutils
        python${{ matrix.python-version }} -m pip install --upgrade pip setuptools pytest

    - name: Compile and install
      run: python${{ matrix.python-version }} -m pip install .

    - name: Execute pytest
      run: python${{ matrix.python-version }} -m pytest
